# Generated by Django 6.1 on 2026-09-28 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skill_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='stared_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
